services:
  - type: web
    name: HALDemo
    env: python
    repo: https://github.com/prakyath-07/agora-server
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: APP_ID
        sync: false
      - key: ACCESS_KEY
        sync: false
      - key: BUCKET_NAME
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CUSTOMER_KEY
        sync: false
      - key: CUSTOMER_SECRET
        sync: false
      - key: TEMP_TOKEN
        sync: false
