services:
  - type: web
    name: Agora Server
    env: python
    repo: https://github.com/prakyath-07/agora-server
    rootDir: .
    buildCommand: pip install flask flask-cors requests gunicorn
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: APP_ID
        sync: false
      - key: ACCESS_KEY
        sync: false
      - key: BUCKET_NAME
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CUSTOMER_KEY
        sync: false
      - key: CUSTOMER_SECRET
        sync: false
